// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type EmailOutbox struct {
	ID           int64          `json:"id"`
	UserID       sql.NullInt64  `json:"user_id"`
	Recipient    string         `json:"recipient"`
	Subject      string         `json:"subject"`
	TemplateName string         `json:"template_name"`
	TemplateData sql.NullString `json:"template_data"`
	RenderedHtml sql.NullString `json:"rendered_html"`
	Status       string         `json:"status"`
	Attempts     int64          `json:"attempts"`
	MaxAttempts  int64          `json:"max_attempts"`
	LastError    sql.NullString `json:"last_error"`
	NextRetryAt  sql.NullTime   `json:"next_retry_at"`
	SentAt       sql.NullTime   `json:"sent_at"`
	CreatedAt    time.Time      `json:"created_at"`
}

type EmailTemplateContent struct {
	ID           int64          `json:"id"`
	TemplateName string         `json:"template_name"`
	BlockName    string         `json:"block_name"`
	Lang         string         `json:"lang"`
	Content      string         `json:"content"`
	UpdatedBy    sql.NullString `json:"updated_by"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Fee struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	LevelID     int64     `json:"level_id"`
	PeriodStart time.Time `json:"period_start"`
	Amount      string    `json:"amount"`
	CreatedAt   time.Time `json:"created_at"`
}

type Level struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Amount    string    `json:"amount"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
}

type Payment struct {
	ID              int64          `json:"id"`
	UserID          sql.NullInt64  `json:"user_id"`
	Date            time.Time      `json:"date"`
	Amount          string         `json:"amount"`
	Kind            string         `json:"kind"`
	KindID          string         `json:"kind_id"`
	LocalAccount    string         `json:"local_account"`
	RemoteAccount   string         `json:"remote_account"`
	Identification  string         `json:"identification"`
	RawData         sql.NullString `json:"raw_data"`
	StaffComment    sql.NullString `json:"staff_comment"`
	CreatedAt       time.Time      `json:"created_at"`
	ProjectID       sql.NullInt64  `json:"project_id"`
	DismissedAt     interface{}    `json:"dismissed_at"`
	DismissedBy     interface{}    `json:"dismissed_by"`
	DismissedReason interface{}    `json:"dismissed_reason"`
}

type Project struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	PaymentsID  sql.NullString `json:"payments_id"`
	Description sql.NullString `json:"description"`
}

type ProjectV struct {
	ID        int64          `json:"id"`
	ProjectID int64          `json:"project_id"`
	Vs        string         `json:"vs"`
	Note      sql.NullString `json:"note"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Reservation struct {
	ID         int64          `json:"id"`
	ResourceID int64          `json:"resource_id"`
	UserID     int64          `json:"user_id"`
	StartsAt   string         `json:"starts_at"`
	EndsAt     string         `json:"ends_at"`
	Note       sql.NullString `json:"note"`
	State      string         `json:"state"`
	EndedBy    sql.NullInt64  `json:"ended_by"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Resource struct {
	ID            int64          `json:"id"`
	Slug          string         `json:"slug"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	State         string         `json:"state"`
	BlockedReason sql.NullString `json:"blocked_reason"`
	Capabilities  string         `json:"capabilities"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type RevbankAccount struct {
	ID                int64         `json:"id"`
	Username          string        `json:"username"`
	UserID            sql.NullInt64 `json:"user_id"`
	BalanceCents      int64         `json:"balance_cents"`
	LastTransactionAt sql.NullTime  `json:"last_transaction_at"`
	SyncedAt          time.Time     `json:"synced_at"`
}

type RevbankTransaction struct {
	ID             int64          `json:"id"`
	TransactionID  string         `json:"transaction_id"`
	Username       string         `json:"username"`
	UserID         sql.NullInt64  `json:"user_id"`
	AmountCents    int64          `json:"amount_cents"`
	Description    string         `json:"description"`
	CounterAccount sql.NullString `json:"counter_account"`
	CreatedAt      time.Time      `json:"created_at"`
	SyncedAt       time.Time      `json:"synced_at"`
}

type Setting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SystemLog struct {
	ID        int64          `json:"id"`
	Subsystem string         `json:"subsystem"`
	Level     string         `json:"level"`
	UserID    sql.NullInt64  `json:"user_id"`
	Message   string         `json:"message"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID                int64          `json:"id"`
	KeycloakID        sql.NullString `json:"keycloak_id"`
	Email             string         `json:"email"`
	Username          sql.NullString `json:"username"`
	Realname          sql.NullString `json:"realname"`
	Phone             sql.NullString `json:"phone"`
	AltContact        sql.NullString `json:"alt_contact"`
	LevelID           int64          `json:"level_id"`
	LevelActualAmount string         `json:"level_actual_amount"`
	PaymentsID        sql.NullString `json:"payments_id"`
	DateJoined        time.Time      `json:"date_joined"`
	KeysGranted       sql.NullTime   `json:"keys_granted"`
	KeysReturned      sql.NullTime   `json:"keys_returned"`
	State             string         `json:"state"`
	IsCouncil         bool           `json:"is_council"`
	IsStaff           bool           `json:"is_staff"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	Locale            string         `json:"locale"`
}
